language: node_js
node_js:
  - "iojs"
addons:
  apt:
    packages:
      - xvfb
script:
  - npm run build
  - npm run test
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &